name: test

on:
    workflow_dispatch:
env:
    murad: hello murad


jobs:
    hello_world:
        env:
            ferid: hello ferid

        runs-on: ubuntu-22.04
        steps:
            - name: job1 step 1
              env:
                nesib: salam nesib
              run: |
                echo "hello world"
                echo "murad: $murad"
                echo "ferid: $ferid"
                echo "nesib: $nesib"

    test2:
        runs-on: ubuntu-latest
        steps:
            - run: print("hello world")
              shell: python
              
    test3:
        runs-on: ubuntu-22.04
        needs:
            - hello_world
            - test2
        steps:
            - name: continuing
              run: "murad: $murad"
            - name: end
              run: print("end")
              shell: python


